"""The sim-facing contract: event types, the SimSource interface and session time.

Depends on nothing else in LocalTC, so any component can import it on any OS.
"""

from localtc.sim_api.airport import Airport, Frequency, ParkingSpot, Runway, RunwayEnd, TaxiPath, TaxiPoint
from localtc.sim_api.clock import Clock, SessionClock, StreamClock
from localtc.sim_api.commands import AnySimCommand, RequestAirportData, SetComFrequency, SimCommand
from localtc.sim_api.codec import decode_event, encode_event
from localtc.sim_api.events import (
    ATC_EVENT_TYPES,
    BUS_EVENT_TYPES,
    RADIO_EVENT_TYPES,
    SIM_EVENT_TYPES,
    AircraftIdentity,
    AirportData,
    AtcAlert,
    AtcEvent,
    AtisBroadcast,
    AtcTransmission,
    BusEvent,
    ConnectionStatus,
    Event,
    LlmExchange,
    OwnshipState,
    PhaseChanged,
    PttPressed,
    PttReleased,
    RadioEvent,
    RadioTuned,
    ReadbackEvaluated,
    SessionInfo,
    SessionNote,
    SimEvent,
    SimLifecycle,
    TrafficSnapshot,
    TrafficTarget,
    Transcript,
    event_type,
)
from localtc.sim_api.source import SimSource, SourceUnavailable

__all__ = [
    "ATC_EVENT_TYPES",
    "BUS_EVENT_TYPES",
    "RADIO_EVENT_TYPES",
    "SIM_EVENT_TYPES",
    "AircraftIdentity",
    "Airport",
    "AirportData",
    "AnySimCommand",
    "AtcAlert",
    "AtcEvent",
    "AtisBroadcast",
    "AtcTransmission",
    "BusEvent",
    "Clock",
    "ConnectionStatus",
    "Event",
    "Frequency",
    "LlmExchange",
    "OwnshipState",
    "ParkingSpot",
    "PhaseChanged",
    "PttPressed",
    "PttReleased",
    "RadioEvent",
    "RadioTuned",
    "ReadbackEvaluated",
    "RequestAirportData",
    "SetComFrequency",
    "Runway",
    "RunwayEnd",
    "SessionClock",
    "SessionInfo",
    "SessionNote",
    "SimCommand",
    "SimEvent",
    "SimLifecycle",
    "SimSource",
    "SourceUnavailable",
    "StreamClock",
    "TaxiPath",
    "TaxiPoint",
    "TrafficSnapshot",
    "TrafficTarget",
    "Transcript",
    "decode_event",
    "encode_event",
    "event_type",
]
